### ISSUE TITLE
Analizar y diseñar la estructura de la aplicación.

### ISSUE THREAD

**Issue by Migueerm** [Migueerm/proyecto-tscdia-1#4]

**Comment by Flor3ncia-Andr4d4** [comment]
**Análisis:** En nuestro grupo, identificamos una necesidad en el ámbito educativo y decidimos desarrollar una aplicación para ayudar a los usuarios a gestionar sus tareas académicas. Nuestra idea se concretó en un sistema de gestión de tareas que permite a los usuarios registrar sus materias, anotar tareas y organizarlas en categorías de manera eficiente.

Nuestro objetivo principal fue diseñar una estructura amigable y accesible para el usuario, asegurando que la interfaz sea intuitiva y fácil de usar desde el primer momento. Nos enfocamos en la simplicidad y la funcionalidad para evitar que el sistema resultara abrumador para los nuevos usuarios.

La aplicación no solo facilita el seguimiento de las tareas y materias, sino que también ofrece funcionalidades como marcar tareas como completas, modificar su estado y listar todas las tareas existentes. Además, proporciona una lista de categorías para una mejor organización.

Nuestro objetivo es que el  sistema de gestión de tareas está diseñado para mejorar la organización y la productividad de los usuarios en el ámbito educativo, brindándoles una herramienta eficaz y fácil de usar para gestionar sus responsabilidades académicas. 

**Diseño de estructura:**
Lo realicé basándose en como se definió el código de evidencia 3:  

.......
